### ISSUE TITLE
Добавить файл конфигурации сервера

### ISSUE THREAD

**Issue by tmcgroul** [seven48/meloman#21]
В нём должны быть настройки, которые указывают серверу:
* порт
* путь к монге

**Comment by tmcgroul** [comment]
@BehindLoader а ваще надо чё-то такое делать?
С одной стороны все эти настройки можно писать в `.env`, но `.env` не пушится. А условный `config.json` задавал настройки по умолчанию.

**Comment by tmcgroul** [comment]
Хм, но пушить его тоже не нужно. Тогда, наверное, нужно проверять `.env` на наличие переменных, а в случае отсутствия - какие-то настройки по умолчанию.

**Comment by BehindLoader** [comment]
> Хм, но пушить его тоже не нужно. Тогда, наверное, нужно проверять `.env` на наличие переменных, а в случае отсутствия - какие-то настройки по умолчанию.

Я так и делаю [вот тут](https://github.com/seven48/meloman/blob/master/utils/logger.js). 
```
const LOG_PATH = process.env.LOG_PATH || './log.txt'
```
Из дотенва загружаю переменную, но если ее нет, то ставлю значение по умолчанию.

**Comment by tmcgroul** [comment]
Дякую
