### ISSUE TITLE
#server ORM прописать модели

### ISSUE THREAD

**Issue by BehindLoader** [seven48/meloman#8]
для
* Альбома
* Тега (жанра)
* Очередь парсинга для тегов (что необходимо еще распарсить)

**Comment by BehindLoader** [comment]
**Примерная схема базы данных**

Очередь:
* Тег
* Ссылка на него

Альбом
* Название STRING
* Исполнитель STRING
* Теги ARRAY<FOREIGN> (тут можно связь на модель Тег закинуть)
* Ссылка на обложку альбома STRING
* Массив треков ARRAY<OBJ>
* * Название трека STRING
* * Linked BOOLEAN (если `False`, то трек прослушать нельзя (но мы договрились, что я тебе такой слать не буду))
* * Ссылка на трек STRING

Тег
* Название тега STRING

**Comment by tmcgroul** [comment]
@BehindLoader 
> Теги ARRAY (тут можно связь на модель Тег закинуть)

А если к этому моменту тэг ещё не будет распарсен?
Ну и в треки флаг на возможность прослушивания добавлять не хочу.

**Comment by BehindLoader** [comment]
@tmcgroul
> А если к этому моменту тэг ещё не будет распарсен?

Ну тогда без связи можно
А если тег не распаршен его можно в очередь кидать тогда

> Ну и в треки флаг на возможность прослушивания добавлять не хочу.

Я тебе просто отдавать такие не буду. На стороне бота валидация будет

**Comment by tmcgroul** [comment]
@BehindLoader 
> А если тег не распаршен его можно в очередь кидать тогда

Ух, ну это не так просто. Ну вот кинул я его в очередь, появилась у меня ссылка на тег в очереди, но ведь нужна ссылка на тег из коллекции тегов. В таком случае очередь должна сразу создавать тэг в коллекции с тэгами, брать сцылку на этот тег и уже её записывать в очередь.

**Comment by BehindLoader** [comment]
@tmcgroul 
Согласен. Давай так
